### ISSUE TITLE
Installation issue on ubuntu 24.04.1 

### ISSUE THREAD

**Issue by GreenShyDude** [aflaag/pokemon-icat#14]
During the installation the program returns this output:
```
+ rm -rf venv
+ python3 -m venv venv
+ source venv/bin/activate
install.sh: 16: source: not found
```
Python depen dency are installed and kitty is installed
the venv directoy is create successfully during the process and the file activate  is there

**Comment by DavideGalilei** [comment]
This is because `source` is a bash builtin, and it's not present in `sh`. I tried to fix this in https://github.com/aflaag/pokemon-icat/pull/15, please check if it works in my fork's `fix-sh-install` branch:
- `git clone https://github.com/DavideGalilei/pokemon-icat.git`
- `git checkout fix-sh-install`
- `sh install.sh` or `./install.sh` (please try both)

**Comment by GreenShyDude** [comment]
Oki, I'll try it asap and give you a feedback, thanks for the support

**Comment by DavideGalilei** [comment]
@GreenShyDude hi, is there any update?

**Comment by GreenShyDude** [comment]
the installation seems fine with both commands but i cant execute the program unless I manually run the executable that is located in the folder .cache/pokemon-icat, if i run it manually it works fine but if i try the command the terminal doesn't find it (tried on kitty).
The executable still in the same folder even after a reboot and if i run it works flawless even with parameters for generations or shiny-probability

**Comment by DavideGalilei** [comment]
The reason for that is because the executable isn't inserted in the global $PATH, I don't know whether that is out of scope for the installer or not. Perhaps @aflaag has an opinion about this. You can add it to the $PATH in your `.bashrc`.
```bash
export PATH="$PATH:~/.cache/pokemon-icat"
```

Either way, thanks for testing, the installation issue seems to have been solved now.

**Comment by aflaag** [comment]
yep i believe it is out of the scope of the installer, i wouldn't want this program to be put in $PATH as of right now
